services:
  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
